# services:
#   - type: web
#     name: nginx-microservices-proxy
#     env: node
#     plan: free
#     buildCommand: npm install
#     startCommand: npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 10000

services:
  - type: web
    name: nginx-proxy
    runtime: docker
    plan: free
    region: oregon  # Choose your preferred region
    branch: main    # Specify your git branch
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    
    # Environment variables
    envVars:
      - key: NGINX_ENV
        value: production
      
    # Health check configuration
    healthCheckPath: /health
    
    # Custom start command (optional, dockerfile CMD will be used by default)
    # startCommand: nginx -g 'daemon off;'
    
    # Auto-deploy settings
    autoDeploy: true