# services:
#   - type: web
#     name: nginx-microservices-proxy
#     env: node
#     plan: free
#     buildCommand: npm install
#     startCommand: npm start
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 10000

services:
  - type: web
    name: nginx-proxy
    runtime: docker
    dockerfilePath: Dockerfile  # Explicitly specify path
    plan: free
    envVars:
      - key: NGINX_ENV
        value: production